### ISSUE TITLE
Misc selectors

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/soupsieve#37]
- [x] `:playing` / `:paused` is for media stuff.  We can't play or pause in our environment, so this will just match nothing (#39).
- [x] `:local-link` this will most likely match nothing (#39).
- [x] `:user-invalid` there can be no user interaction in our environment, so this will match nothing (#39).
- [x] `:scope` ~~I really need to understand what this really is.  From what I understand right now, it would mainly just match `:root`, but I need to research this more, or understand what the future goal for this is.~~. Match `:root` if the document is under select or match, or match the tag if a tag is under match or select. It is used to make a pattern relative to the tag under evaluation. (#38)

**Comment by facelessuser** [comment]
I think I understand `:scope` now.  When calling `querySelector` on an element instead of `document`, the calling element is the **scope**. If called on the document, **root** is the **scope**.  In a CSS document that isn't being called on a specific element but applied to the whole document, and there isn't currently a way to specify a scope, the **scope** is **root**.

This is easy to implement.

**Comment by facelessuser** [comment]
Removed `:blank` from list as it isn't really fleshed out in the spec yet, and so we cannot implement it. Moved it to its own task #40 for possible future implementation.

**Comment by facelessuser** [comment]
Closed by #39
